
version: '3.8'

services:
  api:
    build: ./backend
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    networks:
      - user-dashboard-local
    environment:
      DATABASE_URI: postgresql+psycopg2://${POSTGRES_USER:-user-dashboard}:${POSTGRES_PASSWORD:-user-dashboard}@db:5432/${POSTGRES_DB:-user-dashboard}
      OIDC_CLIENT_ID: "${OIDC_CLIENT_ID}"
      OIDC_CLIENT_SECRET: "${OIDC_CLIENT_SECRET}"
      OIDC_HOST: "${OIDC_HOST}"
      SECRET_KEY: "${SECRET_KEY}"
      BASE_URL: "${BASE_URL}"
    depends_on:
      - db

  db:
    image: postgres:14
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data/
    networks:
      - user-dashboard-local
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-user-dashboard}
      POSTGRES_USER: ${POSTGRES_USER:-user-dashboard}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-user-dashboard}

volumes:
    db-data:

networks:
  user-dashboard-local: